name: Build and Publish Images
on:
  workflow_dispatch: {}
  workflow_call: 
    outputs:
      image:
        description: The URI of the image
        value: ${{ jobs.build_image.outputs.image }}
    secrets:
      DUPLO_TOKEN:
        description: The token to use for Duplo API calls
        required: true

env:
  DUPLO_HOST: ${{ vars.DUPLO_HOST }}
  DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
  ECR_REGISTRY: "813590939111.dkr.ecr.us-west-2.amazonaws.com"


jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    outputs:
      image: ${{ steps.build_image.outputs.uri }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Duplo Setup
      uses: duplocloud/actions/setup@main

    - name: Build and Push Frontend Docker Image
      id: build_image
      uses: duplocloud/actions/build-image@main
      with:
        platforms: linux/amd64
        push: true
        registry: ${{ env.ECR_REGISTRY }}
        repo: "${{ vars.DUPLO_TENANT_BASE }}-prod-frontend"
        build-args: >
          name=${{ github.repository }}

    # https://github.com/docker/buildx/issues/1513
    # I couldnt seem to get the docker image build to work in a way that is compatible with Lambda
    - name: Build Lambda Function
      run: |
        cd lambda
        docker build -t lambda .
        docker tag lambda ${{ env.ECR_REGISTRY }}/${{ vars.DUPLO_TENANT_BASE }}-prod-serverless:main
        docker push ${{ env.ECR_REGISTRY }}/${{ vars.DUPLO_TENANT_BASE }}-prod-serverless:main
